// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.5
// 	protoc        v5.29.3
// source: cst.proto

package cst

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Enum for payment channel types
type ChannelType int32

const (
	ChannelType_CHANNEL_UNKNOWN ChannelType = 0
	ChannelType_CHANNEL_WX      ChannelType = 1 // WeChat
	ChannelType_CHANNEL_ALIPAY  ChannelType = 2 // Alipay
)

// Enum value maps for ChannelType.
var (
	ChannelType_name = map[int32]string{
		0: "CHANNEL_UNKNOWN",
		1: "CHANNEL_WX",
		2: "CHANNEL_ALIPAY",
	}
	ChannelType_value = map[string]int32{
		"CHANNEL_UNKNOWN": 0,
		"CHANNEL_WX":      1,
		"CHANNEL_ALIPAY":  2,
	}
)

func (x ChannelType) Enum() *ChannelType {
	p := new(ChannelType)
	*p = x
	return p
}

func (x ChannelType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ChannelType) Descriptor() protoreflect.EnumDescriptor {
	return file_cst_proto_enumTypes[0].Descriptor()
}

func (ChannelType) Type() protoreflect.EnumType {
	return &file_cst_proto_enumTypes[0]
}

func (x ChannelType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ChannelType.Descriptor instead.
func (ChannelType) EnumDescriptor() ([]byte, []int) {
	return file_cst_proto_rawDescGZIP(), []int{0}
}

// Enum for payment methods
type PayMethod int32

const (
	PayMethod_METHOD_UNKNOWN     PayMethod = 0
	PayMethod_METHOD_CREDIT_CARD PayMethod = 1 // Credit Card
	PayMethod_METHOD_PAYPAL      PayMethod = 2 // PayPal
)

// Enum value maps for PayMethod.
var (
	PayMethod_name = map[int32]string{
		0: "METHOD_UNKNOWN",
		1: "METHOD_CREDIT_CARD",
		2: "METHOD_PAYPAL",
	}
	PayMethod_value = map[string]int32{
		"METHOD_UNKNOWN":     0,
		"METHOD_CREDIT_CARD": 1,
		"METHOD_PAYPAL":      2,
	}
)

func (x PayMethod) Enum() *PayMethod {
	p := new(PayMethod)
	*p = x
	return p
}

func (x PayMethod) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PayMethod) Descriptor() protoreflect.EnumDescriptor {
	return file_cst_proto_enumTypes[1].Descriptor()
}

func (PayMethod) Type() protoreflect.EnumType {
	return &file_cst_proto_enumTypes[1]
}

func (x PayMethod) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PayMethod.Descriptor instead.
func (PayMethod) EnumDescriptor() ([]byte, []int) {
	return file_cst_proto_rawDescGZIP(), []int{1}
}

// Enum for payment status
type PayStatus int32

const (
	PayStatus_STATUS_UNKNOWN   PayStatus = 0
	PayStatus_STATUS_PENDING   PayStatus = 1 // Pending Payment
	PayStatus_STATUS_COMPLETED PayStatus = 2 // Payment Completed
	PayStatus_STATUS_REFUNDING PayStatus = 3 // Refund In Process
	PayStatus_STATUS_REFUNDED  PayStatus = 4 // Refunded
)

// Enum value maps for PayStatus.
var (
	PayStatus_name = map[int32]string{
		0: "STATUS_UNKNOWN",
		1: "STATUS_PENDING",
		2: "STATUS_COMPLETED",
		3: "STATUS_REFUNDING",
		4: "STATUS_REFUNDED",
	}
	PayStatus_value = map[string]int32{
		"STATUS_UNKNOWN":   0,
		"STATUS_PENDING":   1,
		"STATUS_COMPLETED": 2,
		"STATUS_REFUNDING": 3,
		"STATUS_REFUNDED":  4,
	}
)

func (x PayStatus) Enum() *PayStatus {
	p := new(PayStatus)
	*p = x
	return p
}

func (x PayStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PayStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_cst_proto_enumTypes[2].Descriptor()
}

func (PayStatus) Type() protoreflect.EnumType {
	return &file_cst_proto_enumTypes[2]
}

func (x PayStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PayStatus.Descriptor instead.
func (PayStatus) EnumDescriptor() ([]byte, []int) {
	return file_cst_proto_rawDescGZIP(), []int{2}
}

var File_cst_proto protoreflect.FileDescriptor

var file_cst_proto_rawDesc = string([]byte{
	0x0a, 0x09, 0x63, 0x73, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x03, 0x63, 0x73, 0x74,
	0x2a, 0x46, 0x0a, 0x0b, 0x43, 0x68, 0x61, 0x6e, 0x6e, 0x65, 0x6c, 0x54, 0x79, 0x70, 0x65, 0x12,
	0x13, 0x0a, 0x0f, 0x43, 0x48, 0x41, 0x4e, 0x4e, 0x45, 0x4c, 0x5f, 0x55, 0x4e, 0x4b, 0x4e, 0x4f,
	0x57, 0x4e, 0x10, 0x00, 0x12, 0x0e, 0x0a, 0x0a, 0x43, 0x48, 0x41, 0x4e, 0x4e, 0x45, 0x4c, 0x5f,
	0x57, 0x58, 0x10, 0x01, 0x12, 0x12, 0x0a, 0x0e, 0x43, 0x48, 0x41, 0x4e, 0x4e, 0x45, 0x4c, 0x5f,
	0x41, 0x4c, 0x49, 0x50, 0x41, 0x59, 0x10, 0x02, 0x2a, 0x4a, 0x0a, 0x09, 0x50, 0x61, 0x79, 0x4d,
	0x65, 0x74, 0x68, 0x6f, 0x64, 0x12, 0x12, 0x0a, 0x0e, 0x4d, 0x45, 0x54, 0x48, 0x4f, 0x44, 0x5f,
	0x55, 0x4e, 0x4b, 0x4e, 0x4f, 0x57, 0x4e, 0x10, 0x00, 0x12, 0x16, 0x0a, 0x12, 0x4d, 0x45, 0x54,
	0x48, 0x4f, 0x44, 0x5f, 0x43, 0x52, 0x45, 0x44, 0x49, 0x54, 0x5f, 0x43, 0x41, 0x52, 0x44, 0x10,
	0x01, 0x12, 0x11, 0x0a, 0x0d, 0x4d, 0x45, 0x54, 0x48, 0x4f, 0x44, 0x5f, 0x50, 0x41, 0x59, 0x50,
	0x41, 0x4c, 0x10, 0x02, 0x2a, 0x74, 0x0a, 0x09, 0x50, 0x61, 0x79, 0x53, 0x74, 0x61, 0x74, 0x75,
	0x73, 0x12, 0x12, 0x0a, 0x0e, 0x53, 0x54, 0x41, 0x54, 0x55, 0x53, 0x5f, 0x55, 0x4e, 0x4b, 0x4e,
	0x4f, 0x57, 0x4e, 0x10, 0x00, 0x12, 0x12, 0x0a, 0x0e, 0x53, 0x54, 0x41, 0x54, 0x55, 0x53, 0x5f,
	0x50, 0x45, 0x4e, 0x44, 0x49, 0x4e, 0x47, 0x10, 0x01, 0x12, 0x14, 0x0a, 0x10, 0x53, 0x54, 0x41,
	0x54, 0x55, 0x53, 0x5f, 0x43, 0x4f, 0x4d, 0x50, 0x4c, 0x45, 0x54, 0x45, 0x44, 0x10, 0x02, 0x12,
	0x14, 0x0a, 0x10, 0x53, 0x54, 0x41, 0x54, 0x55, 0x53, 0x5f, 0x52, 0x45, 0x46, 0x55, 0x4e, 0x44,
	0x49, 0x4e, 0x47, 0x10, 0x03, 0x12, 0x13, 0x0a, 0x0f, 0x53, 0x54, 0x41, 0x54, 0x55, 0x53, 0x5f,
	0x52, 0x45, 0x46, 0x55, 0x4e, 0x44, 0x45, 0x44, 0x10, 0x04, 0x42, 0x07, 0x5a, 0x05, 0x2e, 0x2f,
	0x63, 0x73, 0x74, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
})

var (
	file_cst_proto_rawDescOnce sync.Once
	file_cst_proto_rawDescData []byte
)

func file_cst_proto_rawDescGZIP() []byte {
	file_cst_proto_rawDescOnce.Do(func() {
		file_cst_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_cst_proto_rawDesc), len(file_cst_proto_rawDesc)))
	})
	return file_cst_proto_rawDescData
}

var file_cst_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_cst_proto_goTypes = []any{
	(ChannelType)(0), // 0: cst.ChannelType
	(PayMethod)(0),   // 1: cst.PayMethod
	(PayStatus)(0),   // 2: cst.PayStatus
}
var file_cst_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_cst_proto_init() }
func file_cst_proto_init() {
	if File_cst_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_cst_proto_rawDesc), len(file_cst_proto_rawDesc)),
			NumEnums:      3,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_cst_proto_goTypes,
		DependencyIndexes: file_cst_proto_depIdxs,
		EnumInfos:         file_cst_proto_enumTypes,
	}.Build()
	File_cst_proto = out.File
	file_cst_proto_goTypes = nil
	file_cst_proto_depIdxs = nil
}
