// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.29.3
// source: payment.proto

package payment

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	PayService_PreparePayment_FullMethodName = "/payment.PayService/PreparePayment"
	PayService_RefundApply_FullMethodName    = "/payment.PayService/RefundApply"
)

// PayServiceClient is the client API for PayService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// 微信支付服务
type PayServiceClient interface {
	// 预支付接口
	PreparePayment(ctx context.Context, in *PayRequest, opts ...grpc.CallOption) (*WxPayPrepare, error)
	// 退款申请接口
	RefundApply(ctx context.Context, in *RefundRequest, opts ...grpc.CallOption) (*RefundRsp, error)
}

type payServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewPayServiceClient(cc grpc.ClientConnInterface) PayServiceClient {
	return &payServiceClient{cc}
}

func (c *payServiceClient) PreparePayment(ctx context.Context, in *PayRequest, opts ...grpc.CallOption) (*WxPayPrepare, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(WxPayPrepare)
	err := c.cc.Invoke(ctx, PayService_PreparePayment_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *payServiceClient) RefundApply(ctx context.Context, in *RefundRequest, opts ...grpc.CallOption) (*RefundRsp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RefundRsp)
	err := c.cc.Invoke(ctx, PayService_RefundApply_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PayServiceServer is the server API for PayService service.
// All implementations must embed UnimplementedPayServiceServer
// for forward compatibility.
//
// 微信支付服务
type PayServiceServer interface {
	// 预支付接口
	PreparePayment(context.Context, *PayRequest) (*WxPayPrepare, error)
	// 退款申请接口
	RefundApply(context.Context, *RefundRequest) (*RefundRsp, error)
	mustEmbedUnimplementedPayServiceServer()
}

// UnimplementedPayServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedPayServiceServer struct{}

func (UnimplementedPayServiceServer) PreparePayment(context.Context, *PayRequest) (*WxPayPrepare, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PreparePayment not implemented")
}
func (UnimplementedPayServiceServer) RefundApply(context.Context, *RefundRequest) (*RefundRsp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RefundApply not implemented")
}
func (UnimplementedPayServiceServer) mustEmbedUnimplementedPayServiceServer() {}
func (UnimplementedPayServiceServer) testEmbeddedByValue()                    {}

// UnsafePayServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PayServiceServer will
// result in compilation errors.
type UnsafePayServiceServer interface {
	mustEmbedUnimplementedPayServiceServer()
}

func RegisterPayServiceServer(s grpc.ServiceRegistrar, srv PayServiceServer) {
	// If the following call pancis, it indicates UnimplementedPayServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&PayService_ServiceDesc, srv)
}

func _PayService_PreparePayment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PayRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PayServiceServer).PreparePayment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PayService_PreparePayment_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PayServiceServer).PreparePayment(ctx, req.(*PayRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PayService_RefundApply_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RefundRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PayServiceServer).RefundApply(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PayService_RefundApply_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PayServiceServer).RefundApply(ctx, req.(*RefundRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// PayService_ServiceDesc is the grpc.ServiceDesc for PayService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var PayService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "payment.PayService",
	HandlerType: (*PayServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "PreparePayment",
			Handler:    _PayService_PreparePayment_Handler,
		},
		{
			MethodName: "RefundApply",
			Handler:    _PayService_RefundApply_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "payment.proto",
}
