// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.29.3
// source: wxpay.proto

package wxpay

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	WxPayService_FetchOrderPayInfo_FullMethodName = "/wxpay.WxPayService/FetchOrderPayInfo"
)

// WxPayServiceClient is the client API for WxPayService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// 订单服务
type WxPayServiceClient interface {
	// 订单详情信息
	FetchOrderPayInfo(ctx context.Context, in *WxPayQueryRequest, opts ...grpc.CallOption) (*WxPayQueryResponse, error)
}

type wxPayServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewWxPayServiceClient(cc grpc.ClientConnInterface) WxPayServiceClient {
	return &wxPayServiceClient{cc}
}

func (c *wxPayServiceClient) FetchOrderPayInfo(ctx context.Context, in *WxPayQueryRequest, opts ...grpc.CallOption) (*WxPayQueryResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(WxPayQueryResponse)
	err := c.cc.Invoke(ctx, WxPayService_FetchOrderPayInfo_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// WxPayServiceServer is the server API for WxPayService service.
// All implementations must embed UnimplementedWxPayServiceServer
// for forward compatibility.
//
// 订单服务
type WxPayServiceServer interface {
	// 订单详情信息
	FetchOrderPayInfo(context.Context, *WxPayQueryRequest) (*WxPayQueryResponse, error)
	mustEmbedUnimplementedWxPayServiceServer()
}

// UnimplementedWxPayServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedWxPayServiceServer struct{}

func (UnimplementedWxPayServiceServer) FetchOrderPayInfo(context.Context, *WxPayQueryRequest) (*WxPayQueryResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method FetchOrderPayInfo not implemented")
}
func (UnimplementedWxPayServiceServer) mustEmbedUnimplementedWxPayServiceServer() {}
func (UnimplementedWxPayServiceServer) testEmbeddedByValue()                      {}

// UnsafeWxPayServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to WxPayServiceServer will
// result in compilation errors.
type UnsafeWxPayServiceServer interface {
	mustEmbedUnimplementedWxPayServiceServer()
}

func RegisterWxPayServiceServer(s grpc.ServiceRegistrar, srv WxPayServiceServer) {
	// If the following call pancis, it indicates UnimplementedWxPayServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&WxPayService_ServiceDesc, srv)
}

func _WxPayService_FetchOrderPayInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(WxPayQueryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WxPayServiceServer).FetchOrderPayInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WxPayService_FetchOrderPayInfo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WxPayServiceServer).FetchOrderPayInfo(ctx, req.(*WxPayQueryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// WxPayService_ServiceDesc is the grpc.ServiceDesc for WxPayService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var WxPayService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "wxpay.WxPayService",
	HandlerType: (*WxPayServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "FetchOrderPayInfo",
			Handler:    _WxPayService_FetchOrderPayInfo_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "wxpay.proto",
}
