// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.5
// 	protoc        v5.29.3
// source: finance.proto

package finance

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 支付单位
type PayUnit int32

const (
	PayUnit_PAY_UNIT_UNSPECIFIED PayUnit = 0 // 未指定
	PayUnit_PAY_UNIT_CENT        PayUnit = 1 // 分
	PayUnit_PAY_UNIT_YUAN        PayUnit = 2 // 元
)

// Enum value maps for PayUnit.
var (
	PayUnit_name = map[int32]string{
		0: "PAY_UNIT_UNSPECIFIED",
		1: "PAY_UNIT_CENT",
		2: "PAY_UNIT_YUAN",
	}
	PayUnit_value = map[string]int32{
		"PAY_UNIT_UNSPECIFIED": 0,
		"PAY_UNIT_CENT":        1,
		"PAY_UNIT_YUAN":        2,
	}
)

func (x PayUnit) Enum() *PayUnit {
	p := new(PayUnit)
	*p = x
	return p
}

func (x PayUnit) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PayUnit) Descriptor() protoreflect.EnumDescriptor {
	return file_finance_proto_enumTypes[0].Descriptor()
}

func (PayUnit) Type() protoreflect.EnumType {
	return &file_finance_proto_enumTypes[0]
}

func (x PayUnit) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PayUnit.Descriptor instead.
func (PayUnit) EnumDescriptor() ([]byte, []int) {
	return file_finance_proto_rawDescGZIP(), []int{0}
}

// 订单信息查请求
type FianceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FinanceKeyId  string                 `protobuf:"bytes,1,opt,name=finance_key_id,json=financeKeyId,proto3" json:"finance_key_id,omitempty"` // 订单号
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FianceRequest) Reset() {
	*x = FianceRequest{}
	mi := &file_finance_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FianceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FianceRequest) ProtoMessage() {}

func (x *FianceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_finance_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FianceRequest.ProtoReflect.Descriptor instead.
func (*FianceRequest) Descriptor() ([]byte, []int) {
	return file_finance_proto_rawDescGZIP(), []int{0}
}

func (x *FianceRequest) GetFinanceKeyId() string {
	if x != nil {
		return x.FinanceKeyId
	}
	return ""
}

// 商品信息模型
type FianceKeyRsp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`                                         // 商品唯一标识
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`                                     // 密钥名称
	Private       string                 `protobuf:"bytes,3,opt,name=private,proto3" json:"private,omitempty"`                               // 密钥
	Type          string                 `protobuf:"bytes,4,opt,name=type,proto3" json:"type,omitempty"`                                     // 密钥类型
	MerchantConf  *Merchant              `protobuf:"bytes,5,opt,name=merchant_conf,json=merchantConf,proto3" json:"merchant_conf,omitempty"` // 商户配置
	Enabled       bool                   `protobuf:"varint,6,opt,name=enabled,proto3" json:"enabled,omitempty"`                              // 是否启用
	Unit          PayUnit                `protobuf:"varint,7,opt,name=unit,proto3,enum=finance.PayUnit" json:"unit,omitempty"`               // 支付单位
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FianceKeyRsp) Reset() {
	*x = FianceKeyRsp{}
	mi := &file_finance_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FianceKeyRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FianceKeyRsp) ProtoMessage() {}

func (x *FianceKeyRsp) ProtoReflect() protoreflect.Message {
	mi := &file_finance_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FianceKeyRsp.ProtoReflect.Descriptor instead.
func (*FianceKeyRsp) Descriptor() ([]byte, []int) {
	return file_finance_proto_rawDescGZIP(), []int{1}
}

func (x *FianceKeyRsp) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *FianceKeyRsp) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *FianceKeyRsp) GetPrivate() string {
	if x != nil {
		return x.Private
	}
	return ""
}

func (x *FianceKeyRsp) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *FianceKeyRsp) GetMerchantConf() *Merchant {
	if x != nil {
		return x.MerchantConf
	}
	return nil
}

func (x *FianceKeyRsp) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

func (x *FianceKeyRsp) GetUnit() PayUnit {
	if x != nil {
		return x.Unit
	}
	return PayUnit_PAY_UNIT_UNSPECIFIED
}

// 商户配置
type Merchant struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	MerchantId     string                 `protobuf:"bytes,1,opt,name=merchant_id,json=merchantId,proto3" json:"merchant_id,omitempty"`               // 商户ID
	MerchantCertSn string                 `protobuf:"bytes,2,opt,name=merchant_cert_sn,json=merchantCertSn,proto3" json:"merchant_cert_sn,omitempty"` // 商户序列号
	MerchantApiKey string                 `protobuf:"bytes,3,opt,name=merchant_api_key,json=merchantApiKey,proto3" json:"merchant_api_key,omitempty"` // 接口key
	AppId          string                 `protobuf:"bytes,4,opt,name=app_id,json=appId,proto3" json:"app_id,omitempty"`                              // 应用ID
	Callback       string                 `protobuf:"bytes,5,opt,name=callback,proto3" json:"callback,omitempty"`                                     // 回调地址
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Merchant) Reset() {
	*x = Merchant{}
	mi := &file_finance_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Merchant) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Merchant) ProtoMessage() {}

func (x *Merchant) ProtoReflect() protoreflect.Message {
	mi := &file_finance_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Merchant.ProtoReflect.Descriptor instead.
func (*Merchant) Descriptor() ([]byte, []int) {
	return file_finance_proto_rawDescGZIP(), []int{2}
}

func (x *Merchant) GetMerchantId() string {
	if x != nil {
		return x.MerchantId
	}
	return ""
}

func (x *Merchant) GetMerchantCertSn() string {
	if x != nil {
		return x.MerchantCertSn
	}
	return ""
}

func (x *Merchant) GetMerchantApiKey() string {
	if x != nil {
		return x.MerchantApiKey
	}
	return ""
}

func (x *Merchant) GetAppId() string {
	if x != nil {
		return x.AppId
	}
	return ""
}

func (x *Merchant) GetCallback() string {
	if x != nil {
		return x.Callback
	}
	return ""
}

var File_finance_proto protoreflect.FileDescriptor

var file_finance_proto_rawDesc = string([]byte{
	0x0a, 0x0d, 0x66, 0x69, 0x6e, 0x61, 0x6e, 0x63, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12,
	0x07, 0x66, 0x69, 0x6e, 0x61, 0x6e, 0x63, 0x65, 0x22, 0x35, 0x0a, 0x0d, 0x46, 0x69, 0x61, 0x6e,
	0x63, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x24, 0x0a, 0x0e, 0x66, 0x69, 0x6e,
	0x61, 0x6e, 0x63, 0x65, 0x5f, 0x6b, 0x65, 0x79, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x0c, 0x66, 0x69, 0x6e, 0x61, 0x6e, 0x63, 0x65, 0x4b, 0x65, 0x79, 0x49, 0x64, 0x22,
	0xd8, 0x01, 0x0a, 0x0c, 0x46, 0x69, 0x61, 0x6e, 0x63, 0x65, 0x4b, 0x65, 0x79, 0x52, 0x73, 0x70,
	0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64,
	0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04,
	0x6e, 0x61, 0x6d, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x70, 0x72, 0x69, 0x76, 0x61, 0x74, 0x65, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x70, 0x72, 0x69, 0x76, 0x61, 0x74, 0x65, 0x12, 0x12,
	0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x74, 0x79,
	0x70, 0x65, 0x12, 0x36, 0x0a, 0x0d, 0x6d, 0x65, 0x72, 0x63, 0x68, 0x61, 0x6e, 0x74, 0x5f, 0x63,
	0x6f, 0x6e, 0x66, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x66, 0x69, 0x6e, 0x61,
	0x6e, 0x63, 0x65, 0x2e, 0x4d, 0x65, 0x72, 0x63, 0x68, 0x61, 0x6e, 0x74, 0x52, 0x0c, 0x6d, 0x65,
	0x72, 0x63, 0x68, 0x61, 0x6e, 0x74, 0x43, 0x6f, 0x6e, 0x66, 0x12, 0x18, 0x0a, 0x07, 0x65, 0x6e,
	0x61, 0x62, 0x6c, 0x65, 0x64, 0x18, 0x06, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x65, 0x6e, 0x61,
	0x62, 0x6c, 0x65, 0x64, 0x12, 0x24, 0x0a, 0x04, 0x75, 0x6e, 0x69, 0x74, 0x18, 0x07, 0x20, 0x01,
	0x28, 0x0e, 0x32, 0x10, 0x2e, 0x66, 0x69, 0x6e, 0x61, 0x6e, 0x63, 0x65, 0x2e, 0x50, 0x61, 0x79,
	0x55, 0x6e, 0x69, 0x74, 0x52, 0x04, 0x75, 0x6e, 0x69, 0x74, 0x22, 0xb2, 0x01, 0x0a, 0x08, 0x4d,
	0x65, 0x72, 0x63, 0x68, 0x61, 0x6e, 0x74, 0x12, 0x1f, 0x0a, 0x0b, 0x6d, 0x65, 0x72, 0x63, 0x68,
	0x61, 0x6e, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x6d, 0x65,
	0x72, 0x63, 0x68, 0x61, 0x6e, 0x74, 0x49, 0x64, 0x12, 0x28, 0x0a, 0x10, 0x6d, 0x65, 0x72, 0x63,
	0x68, 0x61, 0x6e, 0x74, 0x5f, 0x63, 0x65, 0x72, 0x74, 0x5f, 0x73, 0x6e, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x0e, 0x6d, 0x65, 0x72, 0x63, 0x68, 0x61, 0x6e, 0x74, 0x43, 0x65, 0x72, 0x74,
	0x53, 0x6e, 0x12, 0x28, 0x0a, 0x10, 0x6d, 0x65, 0x72, 0x63, 0x68, 0x61, 0x6e, 0x74, 0x5f, 0x61,
	0x70, 0x69, 0x5f, 0x6b, 0x65, 0x79, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0e, 0x6d, 0x65,
	0x72, 0x63, 0x68, 0x61, 0x6e, 0x74, 0x41, 0x70, 0x69, 0x4b, 0x65, 0x79, 0x12, 0x15, 0x0a, 0x06,
	0x61, 0x70, 0x70, 0x5f, 0x69, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x61, 0x70,
	0x70, 0x49, 0x64, 0x12, 0x1a, 0x0a, 0x08, 0x63, 0x61, 0x6c, 0x6c, 0x62, 0x61, 0x63, 0x6b, 0x18,
	0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x63, 0x61, 0x6c, 0x6c, 0x62, 0x61, 0x63, 0x6b, 0x2a,
	0x49, 0x0a, 0x07, 0x50, 0x61, 0x79, 0x55, 0x6e, 0x69, 0x74, 0x12, 0x18, 0x0a, 0x14, 0x50, 0x41,
	0x59, 0x5f, 0x55, 0x4e, 0x49, 0x54, 0x5f, 0x55, 0x4e, 0x53, 0x50, 0x45, 0x43, 0x49, 0x46, 0x49,
	0x45, 0x44, 0x10, 0x00, 0x12, 0x11, 0x0a, 0x0d, 0x50, 0x41, 0x59, 0x5f, 0x55, 0x4e, 0x49, 0x54,
	0x5f, 0x43, 0x45, 0x4e, 0x54, 0x10, 0x01, 0x12, 0x11, 0x0a, 0x0d, 0x50, 0x41, 0x59, 0x5f, 0x55,
	0x4e, 0x49, 0x54, 0x5f, 0x59, 0x55, 0x41, 0x4e, 0x10, 0x02, 0x32, 0x52, 0x0a, 0x0e, 0x46, 0x69,
	0x6e, 0x61, 0x6e, 0x63, 0x65, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x40, 0x0a, 0x0f,
	0x46, 0x65, 0x74, 0x63, 0x68, 0x46, 0x69, 0x6e, 0x61, 0x6e, 0x63, 0x65, 0x4b, 0x65, 0x79, 0x12,
	0x16, 0x2e, 0x66, 0x69, 0x6e, 0x61, 0x6e, 0x63, 0x65, 0x2e, 0x46, 0x69, 0x61, 0x6e, 0x63, 0x65,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x15, 0x2e, 0x66, 0x69, 0x6e, 0x61, 0x6e, 0x63,
	0x65, 0x2e, 0x46, 0x69, 0x61, 0x6e, 0x63, 0x65, 0x4b, 0x65, 0x79, 0x52, 0x73, 0x70, 0x42, 0x0b,
	0x5a, 0x09, 0x2e, 0x2f, 0x66, 0x69, 0x6e, 0x61, 0x6e, 0x63, 0x65, 0x62, 0x06, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x33,
})

var (
	file_finance_proto_rawDescOnce sync.Once
	file_finance_proto_rawDescData []byte
)

func file_finance_proto_rawDescGZIP() []byte {
	file_finance_proto_rawDescOnce.Do(func() {
		file_finance_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_finance_proto_rawDesc), len(file_finance_proto_rawDesc)))
	})
	return file_finance_proto_rawDescData
}

var file_finance_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_finance_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_finance_proto_goTypes = []any{
	(PayUnit)(0),          // 0: finance.PayUnit
	(*FianceRequest)(nil), // 1: finance.FianceRequest
	(*FianceKeyRsp)(nil),  // 2: finance.FianceKeyRsp
	(*Merchant)(nil),      // 3: finance.Merchant
}
var file_finance_proto_depIdxs = []int32{
	3, // 0: finance.FianceKeyRsp.merchant_conf:type_name -> finance.Merchant
	0, // 1: finance.FianceKeyRsp.unit:type_name -> finance.PayUnit
	1, // 2: finance.FinanceService.FetchFinanceKey:input_type -> finance.FianceRequest
	2, // 3: finance.FinanceService.FetchFinanceKey:output_type -> finance.FianceKeyRsp
	3, // [3:4] is the sub-list for method output_type
	2, // [2:3] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_finance_proto_init() }
func file_finance_proto_init() {
	if File_finance_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_finance_proto_rawDesc), len(file_finance_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_finance_proto_goTypes,
		DependencyIndexes: file_finance_proto_depIdxs,
		EnumInfos:         file_finance_proto_enumTypes,
		MessageInfos:      file_finance_proto_msgTypes,
	}.Build()
	File_finance_proto = out.File
	file_finance_proto_goTypes = nil
	file_finance_proto_depIdxs = nil
}
